### ISSUE TITLE
Plugin error: OA-file-hider Error

### ISSUE THREAD

**Issue by FS-Code-zz** [Oliver-Akins/file-hider#38]
When I want to activate the plugin I get the error message: Plugin failure: OA-file-hider Error.
In the console I see: Plugin failure: OA-file-hider Error: ENOENT: no such file or directory, open 'R:\Daten\obsidian\NAS-Frank\.obsidian\plugins\file-hider-main\main. js'

What am I doing wrong.

**Comment by Oliver-Akins** [comment]
Hi there,

This is most likely because the plugin is written in Typescript and I don't keep a compiled version of the code in the repo.

If you must install it manually, the compiled main.js can be found in [releases](https://github.com/Oliver-Akins/file-hider/releases/tag/1.1.1). If you can though, I would recommend installing the plugin using Obsidian's plugin manager.

**Comment by FS-Code-zz** [comment]
Hi and thanks for the quick answer. Sorry for my stupidity regarding Github and Typescript. Learned something again. Your plugin is perfect for me. I hide the png files because I don't want to see them in the obsidian tree. It would be even better if I could hide all png files automatically :-) Thanks again!!!

 

Best regards

Frank

 

Von: Oliver ***@***.***> 
Gesendet: Samstag, 11. November 2023 21:10
An: Oliver-Akins/file-hider ***@***.***>
Cc: FS-Code-zz ***@***.***>; Author ***@***.***>
Betreff: Re: [Oliver-Akins/file-hider] Plugin error: OA-file-hider Error (Issue #38)

 

Hi there,

This is most likely because the plugin is written in Typescript and I don't keep a compiled version of the code in the repo.

If you must install it manually, the compiled main.js can be found in releases <https://github.com/Oliver-Akins/file-hider/releases/tag/1.1.1> . If you can though, I would recommend installing the plugin using Obsidian's plugin manager.

**Comment by Oliver-Akins** [comment]
No worries, glad I could help get it sorted out. 

One thing I want to note: you're not stupid for not understanding/knowing the plugin is written in Typescript and what that requires, it's just something that not everyone may know, if I did make you feel stupid, sorry; that wasn't my intent (I was trying to explain why it wouldn't work with the code as it was).

On your note of having it hide files automatically, I've been looking into ways of doing this using RegEx patterns (hiding `.*\.png` would result in all files ending in .png to be hidden automatically), however I haven't gotten a solution up to my standards yet so it isn't something I've even released a beta version of yet.
