### ISSUE TITLE
[Bug] Folder not hidden

### ISSUE THREAD

**Issue by Mara-Li** [Oliver-Akins/file-hider#4]
**Version** : Windows 11 & IOS|IpadOS
**Obsidian version** : (Insider) 0.14.15
**Plugin version** : 1.0.0

Folder aren't hidden after reloading. Settings are not saved when folder are added.

As the #2, I need to reload the plugin to make it saves this settings.

**Comment by Oliver-Akins** [comment]
This has been fixed alongside #2

https://github.com/Oliver-Akins/file-hider/blob/main/src/main.ts#L43-L50
